### ISSUE TITLE
Link para o Slack do README.md está atualmente quebrado

### ISSUE THREAD

**Issue by diegonvs** [ReciHub/BoasVindas#1]
/cc @OtacilioN

**Comment by OtacilioN** [comment]
Opa, valeu Diego é uma issue que precisamos de fato mapear! @ThiagoAugustoSM me dá permissão no Slack please, o link criado foi temporário e expirou, faz-se necessário criar um permanente

**Comment by OtacilioN** [comment]
Done @diegonvs desculpe pela demora, vamos também voltar a utilizar o Slack que tava meio abandonado.
